Update patch set 2
Patch Set 2:

Flake8 Violations: 5
First 2 shown
---
 ./odl-pipeline/lib/tripleo_manager/tripleo_manager.py:14:1: F401 'common.config' imported but unused
 ./odl-pipeline/lib/tripleo_manager/tripleo_manager.py:32:5: F811 redefinition of unused 'config' from line 14

Patch-set: 2