Update patch set 4
Patch Set 4:

Flake8 Violations: 2
First 2 shown
---
 ./sdnvpn/test/functest/testcase_3.py:31:1: F811 redefinition of unused 'test_utils' from line 23
 ./sdnvpn/test/functest/testcase_3.py:96:9: F841 local variable 'start_quagga' is assigned to but never used

Patch-set: 4
Label: Verified=-1