Update patch set 1
Patch Set 1:

Flake8 Violations: 8
First 3 shown
---
 ./odl-pipeline/lib/common/config.py:5:37: W292 no newline at end of file
 ./odl-pipeline/lib/deployment_cloner/deployment_cloner.py:7:1: F401 'common.config' imported but unused
 ./odl-pipeline/lib/deployment_cloner/deployment_cloner.py:26:5: F811 redefinition of unused 'config' from line 7

Patch-set: 1
Label: Verified=-1