Update patch set 1
Patch Set 1: Code-Review-1

bgpvpn test suite is still failing due to flavors with following errors.
(overcloud) bash-4.4# functest testcase run bgpvpn
2018-02-15 08:16:43,895 - functest.ci.run_tests - INFO - Running test case 'bgpvpn'...
2018-02-15 08:17:03,233 - functest.utils.openstack_utils - ERROR - Error: Flavor 'm1.tiny' not found. Available flavors are:
[<Flavor: yardstick-flavor>, <Flavor: storperf>]
2018-02-15 08:17:03,233 - functest.utils.openstack_utils - ERROR - Error [get_instance_status(nova_client)]: 'NoneType' object has no attribute 'id'

I'm looking into it.

Patch-set: 1
Label: Code-Review=-1